/**
 * Topic taxonomy for ambient recall.
 *
 * The axis that actually matters is not "subject" but **volatility**: what makes a fact hard is
 * whether it moves. "Chi era Popper" has the same answer next year; "e uscito l'ultimo episodio"
 * does not. The repository already encodes this split (`web_search` for moving targets,
 * `knowledge_rag` for stable ones), so ambient recall reuses it rather than inventing a second
 * notion of topic.
 */

export const AMBIENT_DOMAINS = [
  'anime',
  'current_events',
  'film_tv',
  'technology',
  'science',
  'psychology',
  'philosophy',
  'history',
  'gaming',
  'music',
] as const;

export type AmbientDomain = (typeof AMBIENT_DOMAINS)[number];

/**
 * How fast a domain's facts go stale.
 *
 * - `live`   - changes daily or faster; only a freshly refreshed source may be quoted.
 * - `slow`   - changes over weeks/months; a cached answer stays true for a while.
 * - `stable` - reference knowledge; cacheable indefinitely and safe to recall from memory.
 */
export type AmbientVolatility = 'live' | 'slow' | 'stable';

export const DOMAIN_VOLATILITY: Readonly<Record<AmbientDomain, AmbientVolatility>> = {
  anime: 'live',
  current_events: 'live',
  film_tv: 'slow',
  technology: 'slow',
  gaming: 'slow',
  music: 'slow',
  science: 'stable',
  psychology: 'stable',
  philosophy: 'stable',
  history: 'stable',
};

/**
 * Domains whose results may be adult.
 *
 * These are not blocked; they are routed through the chat's existing NSFW policy exactly like
 * every other adult surface in the bot, instead of getting a second, conflicting rule.
 */
export const ADULT_CAPABLE_DOMAINS: ReadonlySet<AmbientDomain> = new Set(['anime']);

/**
 * Per-domain trigger lexicons, Italian and English.
 *
 * Deliberately made of words that are *about* the domain rather than words that merely occur in
 * it: "episodio" signals a series, "bello" signals nothing. Entries are matched on word
 * boundaries against the normalized message, so no entry needs to worry about case or accents.
 */
export const DOMAIN_LEXICON: Readonly<Record<AmbientDomain, readonly string[]>> = {
  anime: [
    'anime',
    'manga',
    'episodio',
    'episodi',
    'episode',
    'puntata',
    'puntate',
    'stagione',
    'season',
    'cour',
    'arco narrativo',
    'studio di animazione',
    'seinen',
    'shonen',
    'shounen',
    'shojo',
    'isekai',
    'mecha',
    'slice of life',
    'waifu',
    'otaku',
    'weeb',
    'sub ita',
    'doppiaggio',
    'hentai',
    'ecchi',
    'doujin',
    'ova',
    'light novel',
    'crunchyroll',
    'anilist',
    'myanimelist',
  ],
  current_events: [
    'notizia',
    'notizie',
    'news',
    'oggi',
    'ieri',
    'stamattina',
    'ultim ora',
    'breaking',
    'e successo',
    'cronaca',
    'governo',
    'elezioni',
    'guerra',
    'sciopero',
    'terremoto',
    'attentato',
    'inflazione',
    'borsa',
    'sentenza',
    'decreto',
  ],
  film_tv: [
    'film',
    'movie',
    'cinema',
    'regista',
    'director',
    'attore',
    'attrice',
    'serie tv',
    'serial',
    'netflix',
    'prime video',
    'disney plus',
    'hbo',
    'trailer',
    'sequel',
    'prequel',
    'colonna sonora',
    'oscar',
    'sceneggiatura',
    'box office',
  ],
  technology: [
    'software',
    'hardware',
    'programmazione',
    'programming',
    'codice',
    'linguaggio',
    'framework',
    'libreria',
    'api',
    'database',
    'server',
    'linux',
    'kernel',
    'docker',
    'kubernetes',
    'javascript',
    'typescript',
    'python',
    'rust',
    'golang',
    'compilatore',
    'algoritmo',
    'crittografia',
    'blockchain',
    'gpu',
    'cpu',
    'intelligenza artificiale',
    'machine learning',
    'modello linguistico',
    'open source',
    'repository',
  ],
  science: [
    'scienza',
    'fisica',
    'chimica',
    'biologia',
    'astronomia',
    'quantistica',
    'relativita',
    'evoluzione',
    'genetica',
    'neuroscienze',
    'esperimento',
    'teoria',
    'ricerca scientifica',
    'entropia',
    'termodinamica',
    'dna',
    'particella',
    'galassia',
    'buco nero',
  ],
  psychology: [
    'psicologia',
    'psicologico',
    'psicologica',
    'psicologiche',
    'psiche',
    'terapia',
    'terapeuta',
    'psicologo',
    'psichiatra',
    'ansia',
    'depressione',
    'trauma',
    'attaccamento',
    'narcisismo',
    'empatia',
    'cognitivo',
    'comportamentale',
    'inconscio',
    'freud',
    'jung',
    'bias cognitivo',
    'dissonanza cognitiva',
    'burnout',
    'autostima',
  ],
  philosophy: [
    'filosofia',
    'filosofo',
    'filosofico',
    'filosofica',
    'filosofiche',
    'filosofici',
    'etica',
    'morale',
    'metafisica',
    'epistemologia',
    'ontologia',
    'esistenzialismo',
    'nichilismo',
    'stoicismo',
    'utilitarismo',
    'libero arbitrio',
    'coscienza',
    'senso della vita',
    'nietzsche',
    'kant',
    'platone',
    'aristotele',
    'socrate',
    'heidegger',
    'schopenhauer',
    'wittgenstein',
    'dialettica',
  ],
  history: [
    'storia',
    'storico',
    'storica',
    'storiche',
    'medioevo',
    'rinascimento',
    'impero',
    'romani',
    'guerra mondiale',
    'rivoluzione',
    'antica grecia',
    'antico egitto',
    'secolo',
    'dinastia',
    'battaglia di',
    'risorgimento',
    'fascismo',
    'guerra fredda',
  ],
  gaming: [
    'videogioco',
    'videogiochi',
    'gioco',
    'gaming',
    'steam',
    'playstation',
    'xbox',
    'nintendo',
    'switch',
    'speedrun',
    'boss fight',
    'patch note',
    'gameplay',
    'fps',
    'mmo',
    'roguelike',
    'souls',
    'indie game',
  ],
  music: [
    'musica',
    'canzone',
    'album',
    'brano',
    'concerto',
    'band',
    'cantante',
    'chitarra',
    'batteria',
    'spotify',
    'discografia',
    'tour',
    'featuring',
    'produttore musicale',
    'genere musicale',
  ],
};

/**
 * Phrases that assert something is *current*.
 *
 * They do not name a domain; they raise the volatility of whatever domain was detected, which is
 * what separates "parlami di Frieren" from "e uscito l'ultimo episodio di Frieren".
 */
export const RECENCY_MARKERS: readonly string[] = [
  'ultimo',
  'ultima',
  'ultimi',
  'ultime',
  'nuovo',
  'nuova',
  'nuovi',
  'nuove',
  'appena uscito',
  'appena uscita',
  'e uscito',
  'e uscita',
  'esce',
  'escono',
  'quando esce',
  'oggi',
  'ieri',
  'stasera',
  'questa settimana',
  'adesso',
  'ora',
  'attuale',
  'attualmente',
  'aggiornamento',
  'latest',
  'newest',
  'just released',
  'right now',
  'currently',
];
