import type { KnowledgeDoc } from '../storage/repositories/knowledge.js';

type Seed = Omit<KnowledgeDoc, 'updatedAt'>;

/**
 * Curated knowledge the bot can draw on when relevant (anime/manga/otaku, Asian pop culture, IT/dev,
 * gaming, TV/film). It is retrieved on-demand by keyword overlap and capped, so it adds prompt weight
 * ONLY when the topic comes up — the character stays complex, never monothematic. Extend freely.
 */
export const KNOWLEDGE_SEED: Seed[] = [
  // ---- anime / manga staples ----
  {
    key: 'anime-shonen-big3',
    topic: 'Shōnen big three / modern titans',
    aliases: [
      'shonen',
      'shounen',
      'naruto',
      'bleach',
      'one piece',
      'jujutsu kaisen',
      'demon slayer',
      'kimetsu',
      'my hero academia',
      'boku no hero',
      'chainsaw man',
    ],
    text: 'Classic shōnen pillars: Naruto, Bleach, One Piece. Modern heavy hitters: Jujutsu Kaisen, Demon Slayer (Kimetsu no Yaiba), Chainsaw Man, My Hero Academia.',
    tags: ['anime', 'manga', 'shonen'],
    salience: 0.7,
  },
  {
    key: 'anime-seinen',
    topic: 'Seinen / prestige anime',
    aliases: [
      'seinen',
      'berserk',
      'vinland saga',
      'monster',
      'vagabond',
      'attack on titan',
      'shingeki',
      'aot',
      'evangelion',
      'eva',
      'cowboy bebop',
      'ghost in the shell',
    ],
    text: 'Seinen / prestige tier: Berserk, Vinland Saga, Monster, Vagabond, Attack on Titan (Shingeki no Kyojin), Neon Genesis Evangelion, Cowboy Bebop, Ghost in the Shell.',
    tags: ['anime', 'manga', 'seinen'],
    salience: 0.7,
  },
  {
    key: 'anime-romcom-slice',
    topic: 'Rom-com / slice-of-life / waifu bait',
    aliases: [
      'romcom',
      'slice of life',
      'oshi no ko',
      'spy x family',
      'bocchi',
      'k-on',
      'lucky star',
      'rezero',
      're:zero',
      'quintessential quintuplets',
      'gotoubun',
      'kaguya',
      'horimiya',
    ],
    text: 'Waifu-heavy / slice-of-life & rom-com: Spy x Family, Oshi no Ko, Bocchi the Rock, Re:Zero, Quintessential Quintuplets (Gotoubun), Kaguya-sama, K-On.',
    tags: ['anime', 'waifu', 'romance'],
    salience: 0.75,
  },
  {
    key: 'waifu-icons',
    topic: 'Iconic waifus',
    aliases: [
      'waifu',
      'waifus',
      'rem',
      'asuka',
      'rei ayanami',
      'zero two',
      'darling in the franxx',
      'hatsune miku',
      'marin kitagawa',
      'makima',
      'power',
      'mikasa',
      'nezuko',
      'hinata',
    ],
    text: 'Perennial waifu icons: Rem (Re:Zero), Asuka & Rei (Evangelion), Zero Two (Darling in the FranXX), Makima & Power (Chainsaw Man), Marin Kitagawa (Dress-Up Darling), Mikasa, Hatsune Miku (Vocaloid).',
    tags: ['waifu', 'anime'],
    salience: 0.8,
  },
  {
    key: 'otaku-slang',
    topic: 'Otaku / weeb slang',
    aliases: [
      'otaku',
      'weeb',
      'weeaboo',
      'waifu',
      'husbando',
      'senpai',
      'kawaii',
      'tsundere',
      'yandere',
      'dere',
      'ahegao',
      'oshi',
      'best girl',
      'isekai',
      'NEET',
      'hikikomori',
    ],
    text: 'Weeb lexicon: best girl, oshi (favorite), tsundere/yandere/kuudere archetypes, isekai (transported-to-another-world genre), husbando/waifu, senpai, hikikomori/NEET (shut-in).',
    tags: ['otaku', 'slang'],
    salience: 0.7,
  },
  {
    key: 'manga-platforms',
    topic: 'Where weebs read/watch',
    aliases: [
      'crunchyroll',
      'mangadex',
      'shonen jump',
      'mangaplus',
      'nyaa',
      'fansub',
      'scanlation',
      'simulcast',
    ],
    text: 'Ecosystem: Crunchyroll (simulcast streaming), MangaPlus / Shōnen Jump (official manga), MangaDex & scanlation groups, fansubs, nyaa for the high-seas crowd.',
    tags: ['anime', 'manga', 'platforms'],
    salience: 0.5,
  },
  // ---- asian pop culture ----
  {
    key: 'asia-jpop-kpop',
    topic: 'J-pop / K-pop / idols',
    aliases: [
      'jpop',
      'kpop',
      'k-pop',
      'idol',
      'vocaloid',
      'miku',
      'babymetal',
      'newjeans',
      'blackpink',
      'bts',
      'ado',
      'yoasobi',
      'gacha',
    ],
    text: 'Asian pop: idol culture (oshi = your favorite member), Vocaloid/Hatsune Miku, YOASOBI & Ado (J-pop), NewJeans/BLACKPINK/BTS (K-pop). Gacha games monetize the same idol/waifu instinct.',
    tags: ['music', 'asia', 'idol'],
    salience: 0.55,
  },
  {
    key: 'gacha-games',
    topic: 'Gacha / waifu games',
    aliases: [
      'gacha',
      'genshin',
      'genshin impact',
      'honkai',
      'star rail',
      'hoyoverse',
      'fate grand order',
      'fgo',
      'blue archive',
      'azur lane',
      'nikke',
      'whale',
      'pity',
    ],
    text: 'Gacha gold mines: Genshin Impact & Honkai: Star Rail (HoYoverse), Fate/Grand Order, Blue Archive, Azur Lane, NIKKE. Slang: "whale" (big spender), "pity" (guaranteed pull counter), rolling for waifus.',
    tags: ['gaming', 'gacha', 'waifu'],
    salience: 0.65,
  },
  // ---- IT / dev culture ----
  {
    key: 'it-langs',
    topic: 'Programming languages vibe',
    aliases: [
      'python',
      'rust',
      'javascript',
      'typescript',
      'golang',
      'c++',
      'java',
      'php',
      'haskell',
      'kotlin',
      'zig',
    ],
    text: 'Dev stereotypes: Python = glue/ML, Rust = borrow-checker zealots, JS/TS = web everything, Go = boring-but-ships, C++ = footguns, PHP = the language everyone mocks and still runs the web.',
    tags: ['it', 'dev', 'programming'],
    salience: 0.6,
  },
  {
    key: 'it-culture',
    topic: 'Dev / hacker culture',
    aliases: [
      'linux',
      'arch',
      'arch btw',
      'vim',
      'emacs',
      'neovim',
      'docker',
      'kubernetes',
      'k8s',
      'stack overflow',
      'git',
      'regex',
      'tabs vs spaces',
      'segfault',
      'rubber duck',
    ],
    text: 'Dev brainrot: "I use Arch btw", vim vs emacs holy war, tabs vs spaces, copy-pasting from Stack Overflow, blaming DNS, "works on my machine", regex as dark magic, rubber-duck debugging.',
    tags: ['it', 'dev', 'culture'],
    salience: 0.6,
  },
  {
    key: 'it-ai',
    topic: 'AI / LLM culture',
    aliases: [
      'ai',
      'llm',
      'gpt',
      'chatgpt',
      'stable diffusion',
      'midjourney',
      'local model',
      'ollama',
      'gpu',
      'vram',
      'hallucination',
      'prompt',
      'rag',
      'fine tune',
    ],
    text: 'AI scene: LLMs (GPT, local models via Ollama), Stable Diffusion / Midjourney for images, the GPU/VRAM arms race, "it hallucinated", prompt engineering, RAG, AI waifu chatbots (very on-brand).',
    tags: ['it', 'ai'],
    salience: 0.6,
  },
  {
    key: 'crypto-degen',
    topic: 'Crypto / degen finance',
    aliases: [
      'crypto',
      'bitcoin',
      'btc',
      'ethereum',
      'eth',
      'solana',
      'altcoin',
      'shitcoin',
      'memecoin',
      'rug',
      'rugpull',
      'hodl',
      'dca',
      'ape',
      'ngmi',
      'wagmi',
      'diamond hands',
      'pump',
      'dump',
    ],
    text: 'Degen finance: HODL, DCA (dollar-cost averaging), aping in, rug pulls, memecoins, "ngmi/wagmi", diamond hands, leverage liquidations. Never real financial advice — it is a casino with extra steps.',
    tags: ['crypto', 'finance', 'degen'],
    salience: 0.6,
  },
  // ---- gaming ----
  {
    key: 'gaming-staples',
    topic: 'Gaming staples',
    aliases: [
      'souls',
      'soulslike',
      'elden ring',
      'dark souls',
      'fromsoftware',
      'zelda',
      'tears of the kingdom',
      'baldurs gate',
      'bg3',
      'minecraft',
      'fortnite',
      'league of legends',
      'lol',
      'valorant',
      'cs2',
      'counter strike',
      'gta',
      'speedrun',
    ],
    text: 'Gaming canon: FromSoftware soulslikes (Elden Ring, Dark Souls), Zelda: Tears of the Kingdom, Baldur\'s Gate 3, plus the live-service treadmill (LoL, Valorant, CS2, Fortnite). "Git gud", speedruns, no-hit runs.',
    tags: ['gaming'],
    salience: 0.55,
  },
  // ---- tv / film ----
  {
    key: 'tv-prestige',
    topic: 'Prestige & cult TV',
    aliases: [
      'breaking bad',
      'better call saul',
      'the wire',
      'sopranos',
      'game of thrones',
      'got',
      'succession',
      'true detective',
      'severance',
      'the boys',
      'dark',
      'mr robot',
      'rick and morty',
      'twin peaks',
    ],
    text: 'Prestige/cult TV: Breaking Bad & Better Call Saul, The Wire, The Sopranos, Succession, Severance, True Detective S1, The Boys, Dark, Mr. Robot, Rick and Morty.',
    tags: ['tv', 'series'],
    salience: 0.55,
  },
  {
    key: 'scifi-canon',
    topic: 'Sci-fi / nerd film canon',
    aliases: [
      'blade runner',
      'matrix',
      'dune',
      'star wars',
      'star trek',
      'cyberpunk',
      'akira',
      'ghost in the shell',
      'lotr',
      'lord of the rings',
      'warhammer',
      '40k',
    ],
    text: 'Nerd film/lore canon: Blade Runner, The Matrix, Dune, Star Wars/Trek, Akira & Ghost in the Shell (cyberpunk roots), Lord of the Rings, Warhammer 40k (grimdark, "in the grim darkness of the far future…").',
    tags: ['scifi', 'film', 'nerd'],
    salience: 0.55,
  },
];
